import { Category, Product } from '../types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'crop_protection',
    name: 'Thuốc Bảo Vệ Thực Vật',
    nameEn: 'Crop Protection',
    slug: 'thuoc-bao-ve-thuc-vat',
    icon: 'ShieldAlert',
    type: 'crop_protection',
    description: 'Thuốc trừ sâu, trừ bệnh đạo ôn, thán thư, trừ cỏ và kích thích sinh trưởng chính hãng Syngenta, Bayer, Lộc Trời.',
    descriptionEn: 'Fungicides, insecticides, herbicides, and plant growth regulators.',
    subCategories: [
      { id: 'sau', name: 'Thuốc trừ sâu & rầy', nameEn: 'Insecticides', slug: 'thuoc-tru-sau', parentId: 'crop_protection' },
      { id: 'benh', name: 'Thuốc trừ bệnh & nấm', nameEn: 'Fungicides', slug: 'thuoc-tru-benh', parentId: 'crop_protection' },
      { id: 'co', name: 'Thuốc trừ cỏ', nameEn: 'Herbicides', slug: 'thuoc-tru-co', parentId: 'crop_protection' },
      { id: 'sinh-truong', name: 'Chất điều hòa sinh trưởng', nameEn: 'Growth Regulators', slug: 'dieu-hoa-sinh-truong', parentId: 'crop_protection' },
    ]
  },
  {
    id: 'fertilizer',
    name: 'Phân Bón Dinh Dưỡng',
    nameEn: 'Fertilizers',
    slug: 'phan-bon-dinh-duong',
    icon: 'Sprout',
    type: 'fertilizer',
    description: 'Phân bón NPK Đầu Trâu, DAP Phú Mỹ, phân bón lá vi lượng và phân bón hữu cơ vi sinh cải tạo đất.',
    descriptionEn: 'NPK, DAP, foliar micronutrients and microbial organic fertilizers.',
    subCategories: [
      { id: 'npk', name: 'Phân NPK & Đa lượng', nameEn: 'NPK Compound', slug: 'phan-npk', parentId: 'fertilizer' },
      { id: 'la', name: 'Phân bón lá & Vi lượng', nameEn: 'Foliar Fertilizers', slug: 'phan-bon-la', parentId: 'fertilizer' },
      { id: 'huu-co', name: 'Phân hữu cơ & Vi sinh', nameEn: 'Organic Fertilizers', slug: 'phan-huu-co', parentId: 'fertilizer' },
    ]
  },
  {
    id: 'seeds',
    name: 'Hạt Giống & Lúa Giống',
    nameEn: 'Seeds & Seedlings',
    slug: 'hat-giong-lua-giong',
    icon: 'Wheat',
    type: 'seeds',
    description: 'Lúa giống xác nhận ST25, Đài Thơm 8, hạt giống rau màu F1 Rạng Đông, Trang Nông tỷ lệ nảy mầm > 85%.',
    descriptionEn: 'Certified rice seeds, hybrid vegetable and melon seeds with high germination rate.',
    subCategories: [
      { id: 'lua', name: 'Lúa giống xác nhận', nameEn: 'Certified Rice Seeds', slug: 'lua-giong', parentId: 'seeds' },
      { id: 'rau-mau', name: 'Hạt giống rau màu F1', nameEn: 'Vegetable Seeds', slug: 'hat-giong-rau-mau', parentId: 'seeds' },
      { id: 'hoa-qua', name: 'Hạt giống dưa hấu, ớt, cà chua', nameEn: 'Fruit & Melon Seeds', slug: 'hat-giong-hoa-qua', parentId: 'seeds' },
    ]
  },
  {
    id: 'equipment',
    name: 'Thiết Bị Phun Xịt & Cơ Giới',
    nameEn: 'Sprayers & Equipment',
    slug: 'thiet-bi-phun-xit',
    icon: 'Wrench',
    type: 'equipment',
    description: 'Máy phun thuốc đeo vai động cơ 2 thì/4 thì, bình xịt điện ắc quy 20L, béc phun sương cao áp và phụ tùng thay thế.',
    descriptionEn: 'Knapsack power sprayers, electric battery sprayers, brass nozzles and spare parts.',
    subCategories: [
      { id: 'may-xit-dong-co', name: 'Máy xịt động cơ xăng', nameEn: 'Gasoline Sprayers', slug: 'may-xit-dong-co', parentId: 'equipment' },
      { id: 'binh-xit-dien', name: 'Bình xịt điện ắc quy', nameEn: 'Battery Sprayers', slug: 'binh-xit-dien', parentId: 'equipment' },
      { id: 'phu-tung', name: 'Béc phun, dây xịt, phụ kiện', nameEn: 'Nozzles & Accessories', slug: 'phu-tung-phun-xit', parentId: 'equipment' },
    ]
  }
];

export const MOCK_PRODUCTS: Product[] = [
  // 1. Thuốc BVTV: Anvil 5SC
  {
    id: 'prod-anvil-5sc',
    name: 'Thuốc trừ nấm bệnh Anvil 5SC Syngenta',
    nameEn: 'Anvil 5SC Fungicide Syngenta',
    slug: 'thuoc-tru-benh-anvil-5sc-syngenta',
    sku: 'SYN-ANV-500',
    categoryId: 'crop_protection',
    categoryType: 'crop_protection',
    categoryName: 'Thuốc Bảo Vệ Thực Vật',
    brand: 'Syngenta',
    origin: 'Thụy Sỹ',
    rating: 4.9,
    reviewCount: 128,
    soldCount: 840,
    price: 215000,
    originalPrice: 245000,
    discountPercent: 12,
    stock: 240,
    unit: 'Chai',
    isFeatured: true,
    isBestSeller: true,
    thumbnail: 'https://images.unsplash.com/photo-1592417817098-8f3d6910a30b?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1592417817098-8f3d6910a30b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Đặc trị khô vằn, lem lép hạt trên lúa, rỉ sắt trên cà phê, phấn trắng trên xoài và cao su.',
    description: `Anvil 5SC là thuốc trừ bệnh phổ rộng có tác dụng nội hấp và thấm sâu cực mạnh. Thuốc tiêu diệt nấm bệnh thông qua cơ chế ngăn chặn sinh tổng hợp Ergosterol (thành phần cấu tạo màng tế bào nấm).
    - Giúp cây lúa giữ bộ lá đòng xanh bền bỉ, hạt sáng mẩy, nặng hạt.
    - Hạn chế tối đa hiện tượng rụng lá, khô cành do nấm bệnh trên cây ăn trái và cây công nghiệp.`,
    instructions: 'Pha 40-50ml cho bình 25 lít nước hoặc 350-400ml cho phuy 200 lít nước. Phun khi vết bệnh chớm xuất hiện.',
    variants: [
      { id: 'v-anv-100', name: 'Chai 100ml', price: 65000, originalPrice: 75000, stock: 95, sku: 'SYN-ANV-100' },
      { id: 'v-anv-500', name: 'Chai 500ml', price: 215000, originalPrice: 245000, stock: 120, sku: 'SYN-ANV-500' },
      { id: 'v-anv-1000', name: 'Chai 1000ml (1 Lít)', price: 395000, originalPrice: 430000, stock: 25, sku: 'SYN-ANV-1000' },
    ],
    cropProtectionSpecs: {
      activeIngredients: 'Hexaconazole 50g/L',
      concentration: '50g/L',
      formulation: 'SC (Huyền phù đậm đặc)',
      targetPests: ['Đạo ôn', 'Khô vằn', 'Lem lép hạt', 'Rỉ sắt', 'Thán thư'],
      applicableCrops: ['Lúa', 'Cà phê', 'Cao su', 'Cây ăn trái', 'Rau màu'],
      dosage: '0.8 - 1.0 lít/ha (pha 40-50ml/bình 25L)',
      phi: '14 ngày',
      toxicityLevel: 'GHS 5',
    }
  },

  // 2. Thuốc BVTV: Amistar Top 325SC
  {
    id: 'prod-amistar-top',
    name: 'Thuốc trừ bệnh Amistar Top 325SC Syngenta',
    nameEn: 'Amistar Top 325SC Fungicide',
    slug: 'thuoc-tru-benh-amistar-top-325sc',
    sku: 'SYN-AMI-250',
    categoryId: 'crop_protection',
    categoryType: 'crop_protection',
    categoryName: 'Thuốc Bảo Vệ Thực Vật',
    brand: 'Syngenta',
    origin: 'Thụy Sỹ',
    rating: 5.0,
    reviewCount: 94,
    soldCount: 650,
    price: 320000,
    originalPrice: 350000,
    discountPercent: 9,
    stock: 180,
    unit: 'Chai',
    isFeatured: true,
    thumbnail: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Đặc trị đốm vằn, thán thư hoa quả, phòng trừ lem lép hạt và giúp lá đòng xanh mướt.',
    description: `Amistar Top 325SC là sự kết hợp hoàn hảo giữa 2 hoạt chất tiên tiến Azoxystrobin và Difenoconazole, mang lại tác động kép: phòng ngừa từ bên ngoài và tiêu diệt nấm bệnh bên trong mô thực vật.`,
    instructions: 'Phun vào giai đoạn lúa trổ lẹt xẹt và trổ đều để bảo vệ tối đa năng suất.',
    variants: [
      { id: 'v-ami-100', name: 'Chai 100ml', price: 145000, stock: 80, sku: 'SYN-AMI-100' },
      { id: 'v-ami-250', name: 'Chai 250ml', price: 320000, originalPrice: 350000, stock: 100, sku: 'SYN-AMI-250' },
    ],
    cropProtectionSpecs: {
      activeIngredients: 'Azoxystrobin 200g/L + Difenoconazole 125g/L',
      concentration: '325g/L',
      formulation: 'SC (Huyền phù đậm đặc)',
      targetPests: ['Đốm vằn', 'Lem lép hạt', 'Vàng lá chín sớm', 'Thán thư sầu riêng', 'Đốm lá'],
      applicableCrops: ['Lúa', 'Sầu riêng', 'Xoài', 'Ớt', 'Cà chua'],
      dosage: '25-35ml cho bình 25 lít nước',
      phi: '10 ngày',
      toxicityLevel: 'GHS 4',
    }
  },

  // 3. Phân bón: NPK Đầu Trâu 20-20-15+TE
  {
    id: 'prod-npk-dau-trau-202015',
    name: 'Phân bón NPK Đầu Trâu 20-20-15+TE Bình Điền',
    nameEn: 'Dau Trau Fertilizer NPK 20-20-15+TE',
    slug: 'phan-bon-npk-dau-trau-20-20-15-te',
    sku: 'BD-NPK-202015-25',
    categoryId: 'fertilizer',
    categoryType: 'fertilizer',
    categoryName: 'Phân Bón Dinh Dưỡng',
    brand: 'Bình Điền',
    origin: 'Việt Nam',
    rating: 4.8,
    reviewCount: 210,
    soldCount: 1420,
    price: 485000,
    originalPrice: 510000,
    discountPercent: 5,
    stock: 150,
    unit: 'Bao',
    isFeatured: true,
    isBestSeller: true,
    thumbnail: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Hàm lượng Đạm, Lân, Kali cân bằng bổ sung vi lượng TE giúp cây đâm chồi, nuôi trái to, bóng hạt.',
    description: `Phân bón NPK Đầu Trâu 20-20-15+TE cao cấp chuyên dùng cho các giai đoạn phát triển cành lá, nuôi hoa và nuôi trái non. Bổ sung các nguyên tố vi lượng Kẽm (Zn), Bo (B) giúp chống rụng trái non, chắc hạt và tăng sức đề kháng trước thời tiết khắc nghiệt.`,
    instructions: 'Bón gốc rải đều xung quanh tán cây, kết hợp tưới đủ ẩm sau khi bón.',
    variants: [
      { id: 'v-npk-25kg', name: 'Bao 25kg', price: 485000, originalPrice: 510000, stock: 90, sku: 'BD-NPK-25' },
      { id: 'v-npk-50kg', name: 'Bao 50kg', price: 940000, originalPrice: 990000, stock: 60, sku: 'BD-NPK-50' },
    ],
    fertilizerSpecs: {
      npkRatio: '20% N - 20% P2O5 - 15% K2O',
      micronutrients: 'Bo (B): 50ppm, Kẽm (Zn): 100ppm',
      fertilizerType: 'Gốc',
      dosage: '150 - 250 kg/ha/lần bón tùy loại cây trồng',
      applicableCrops: ['Lúa', 'Cây ăn trái (Bưởi, Cam, Sầu riêng)', 'Cà phê, Tiêu', 'Rau màu'],
    }
  },

  // 4. Phân bón lá: Siêu Ra Rễ Rooting Hợp Trí
  {
    id: 'prod-rooting-hop-tri',
    name: 'Phân bón lá Hợp Trí Super Humic & Rooting',
    nameEn: 'Hop Tri Super Humic Root Booster',
    slug: 'phan-bon-la-hop-tri-super-humic',
    sku: 'HT-HUMIC-1KG',
    categoryId: 'fertilizer',
    categoryType: 'fertilizer',
    categoryName: 'Phân Bón Dinh Dưỡng',
    brand: 'Hợp Trí',
    origin: 'Việt Nam',
    rating: 4.9,
    reviewCount: 88,
    soldCount: 930,
    price: 135000,
    stock: 310,
    unit: 'Gói',
    isNew: true,
    thumbnail: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Kích thích ra rễ tơ cực mạnh, giải độc phèn, hạ mặn và tái tạo bộ rễ sau ngập úng.',
    description: `Hợp Trí Super Humic chiết xuất từ mỏ than bùn cổ sinh Leonardite với hàm lượng Axit Humic đậm đặc tới 70%. Giúp đất tơi xốp, kích thích hệ vi sinh vật có lợi phát triển và tăng khả năng hấp thu phân bón của rễ cây.`,
    instructions: 'Pha 1kg cho 800 - 1000 lít nước tưới quanh gốc hoặc trộn đều với phân NPK để bón lót.',
    variants: [
      { id: 'v-humic-1kg', name: 'Gói 1kg', price: 135000, stock: 250, sku: 'HT-HUM-1KG' },
      { id: 'v-humic-10kg', name: 'Thùng 10 gói (10kg)', price: 1280000, originalPrice: 1350000, stock: 60, sku: 'HT-HUM-10KG' },
    ],
    fertilizerSpecs: {
      organicContent: 'Axit Humic 70%, Kali hữu hiệu (K2Ohh) 10%',
      fertilizerType: 'Lá',
      dosage: 'Pha 20-25g cho bình 25 lít nước hoặc 1kg cho phuy 800L',
      applicableCrops: ['Cây giống, cây con mới trồng', 'Cây sau thu hoạch', 'Lúa sạ', 'Cây ăn trái'],
    }
  },

  // 5. Hạt giống: Lúa Giống ST25 Cấp Xác Nhận
  {
    id: 'prod-lua-giong-st25',
    name: 'Lúa giống xác nhận ST25 (Gạo Ngon Nhất Thế Giới)',
    nameEn: 'Certified Rice Seeds ST25 World Best Rice',
    slug: 'lua-giong-xac-nhan-st25',
    sku: 'LUA-ST25-40KG',
    categoryId: 'seeds',
    categoryType: 'seeds',
    categoryName: 'Hạt Giống & Lúa Giống',
    brand: 'Hồ Quang Trí',
    origin: 'Sóc Trăng, Việt Nam',
    rating: 5.0,
    reviewCount: 312,
    soldCount: 2850,
    price: 360000,
    originalPrice: 390000,
    discountPercent: 8,
    stock: 200,
    unit: 'Bao 20kg',
    isFeatured: true,
    isBestSeller: true,
    thumbnail: 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Hạt giống F1 thuần chủng, bông to, gạo dài trong không bạc bụng, cơm dẻo thơm mùi lá dứa tự nhiên.',
    description: `Giống lúa ST25 do kỹ sư Hồ Quang Cua lai tạo, đạt giải Gạo ngon nhất thế giới. Cây lúa cứng cáp, chịu phèn mặn tốt, ít nhiễm rầy nâu và đạo ôn lá. Phù hợp cơ cấu luân canh lúa - tôm hoặc thâm canh 2-3 vụ/năm.`,
    instructions: 'Ngâm ủ đúng kỹ thuật từ 24-36 tiếng, xả chua trước khi gieo sạ.',
    variants: [
      { id: 'v-st25-20kg', name: 'Bao 20kg', price: 360000, originalPrice: 390000, stock: 120, sku: 'ST25-20K' },
      { id: 'v-st25-40kg', name: 'Bao 40kg', price: 700000, originalPrice: 760000, stock: 80, sku: 'ST25-40K' },
    ],
    seedSpecs: {
      purity: '≥ 99.5%',
      germinationRate: '≥ 85%',
      moisture: '≤ 13.5%',
      growthDuration: '100 - 105 ngày',
      season: 'Vụ Đông Xuân, Hè Thu',
      yield: '6.5 - 7.5 tấn/ha',
    }
  },

  // 6. Hạt giống: Ớt Chỉ Thiên Lai F1 Demon Rạng Đông
  {
    id: 'prod-ot-chi-thien-f1',
    name: 'Hạt giống ớt chỉ thiên lai F1 Demon Rạng Đông',
    nameEn: 'Demon F1 Hot Pepper Seeds',
    slug: 'hat-giong-ot-chi-thien-lai-f1-demon',
    sku: 'RD-OT-DEMON-5G',
    categoryId: 'seeds',
    categoryType: 'seeds',
    categoryName: 'Hạt Giống & Lúa Giống',
    brand: 'Rạng Đông',
    origin: 'Việt Nam',
    rating: 4.7,
    reviewCount: 45,
    soldCount: 520,
    price: 75000,
    stock: 450,
    unit: 'Gói',
    isNew: true,
    thumbnail: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Cây sinh trưởng mạnh, phân nhánh nhiều, quả chỉ thiên đều, cay nồng và chịu lạnh tốt.',
    description: `Giống ớt F1 Demon có khả năng kháng bệnh thán thư và héo xanh vi khuẩn cực tốt. Trái thẳng dài 6-8cm, màu đỏ bóng đẹp mắt, thuận tiện vận chuyển đi xa và xuất khẩu.`,
    instructions: 'Gieo hạt trong bầu ươm 20-25 ngày trước khi cấy ra ruộng.',
    variants: [
      { id: 'v-ot-5g', name: 'Gói 5g (khoảng 800-1000 hạt)', price: 75000, stock: 300, sku: 'RD-OT-5G' },
      { id: 'v-ot-20g', name: 'Gói 20g', price: 260000, stock: 150, sku: 'RD-OT-20G' },
    ],
    seedSpecs: {
      purity: '≥ 99%',
      germinationRate: '≥ 85%',
      moisture: '≤ 8%',
      growthDuration: 'Thu hoạch 75-80 ngày sau trồng',
      season: 'Quanh năm',
      yield: '25 - 30 tấn/ha',
    }
  },

  // 7. Thiết bị: Máy xịt thuốc đeo vai Oshima 767
  {
    id: 'prod-may-xit-oshima-767',
    name: 'Máy phun thuốc đeo vai động cơ 2 thì Oshima 767',
    nameEn: 'Oshima 767 Knapsack Power Sprayer',
    slug: 'may-phun-thuoc-deo-vai-oshima-767',
    sku: 'OSH-767-25L',
    categoryId: 'equipment',
    categoryType: 'equipment',
    categoryName: 'Thiết Bị Phun Xịt & Cơ Giới',
    brand: 'Oshima',
    origin: 'Nhật Bản / Lắp ráp VN',
    rating: 4.9,
    reviewCount: 86,
    soldCount: 340,
    price: 2450000,
    originalPrice: 2750000,
    discountPercent: 11,
    stock: 45,
    unit: 'Máy',
    isFeatured: true,
    thumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Bơm vuông đồng thau cao áp, động cơ 2 thì dễ nổ, dung tích thùng 25 lít chịu lực va đập.',
    description: `Máy xịt thuốc sâu Oshima 767 là dòng máy xịt chuyên dụng cho nhà vườn diện tích lớn, cánh đồng lúa và đồi chè. Sử dụng bộ bơm bằng đồng nguyên khối siêu bền, áp lực xịt mạnh và đều, tiết kiệm nhiên liệu xăng pha nhớt.`,
    instructions: 'Pha xăng với nhớt 2 thì theo tỷ lệ 25:1. Kiểm tra lọc nhớt và bảo dưỡng định kỳ.',
    variants: [
      { id: 'v-osh-25l', name: 'Thùng 25 Lít - Bơm Đồng', price: 2450000, originalPrice: 2750000, stock: 35, sku: 'OSH-767-BR' },
      { id: 'v-osh-full', name: 'Trọn bộ (Kèm cuộn dây xịt 50m)', price: 3100000, stock: 10, sku: 'OSH-767-SET' },
    ],
    equipmentSpecs: {
      capacity: '25 Lít',
      powerType: 'Động cơ xăng 2 thì',
      pressure: '20 - 35 kgf/cm²',
      weight: '9.5 kg',
      warrantyMonths: 12,
    }
  },

  // 8. Thiết bị: Bình xịt điện ắc quy Kasei 20L
  {
    id: 'prod-binh-xit-dien-kasei',
    name: 'Bình xịt điện ắc quy 20L Kasei KS-20C (12V-12Ah)',
    nameEn: 'Kasei KS-20C Electric Battery Sprayer 20L',
    slug: 'binh-xit-dien-ac-quy-kasei-20l',
    sku: 'KAS-KS20C',
    categoryId: 'equipment',
    categoryType: 'equipment',
    categoryName: 'Thiết Bị Phun Xịt & Cơ Giới',
    brand: 'Kasei',
    origin: 'Việt Nam',
    rating: 4.8,
    reviewCount: 105,
    soldCount: 680,
    price: 1150000,
    originalPrice: 1300000,
    discountPercent: 12,
    stock: 70,
    unit: 'Bình',
    isBestSeller: true,
    thumbnail: 'https://images.unsplash.com/photo-1584467735871-8e85353a8413?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1584467735871-8e85353a8413?auto=format&fit=crop&w=800&q=80',
    ],
    shortDescription: 'Ắc quy 12V 12Ah phun liên tục 6-8 giờ (khoảng 20-25 bình), bơm tự ngắt tiết kiệm pin.',
    description: `Bình xịt điện Kasei KS-20C vỏ nhựa dẻo nguyên sinh chịu được mọi loại hóa chất và phân bón lá. Đi kèm cần inox rút dài 1.2m, đồng hồ báo vôn kế hiển thị dung lượng pin chuẩn xác.`,
    instructions: 'Sạc đầy ắc quy 6-8 tiếng trước khi sử dụng vụ mùa. Không để bình cạn pin quá lâu.',
    variants: [
      { id: 'v-kas-12ah', name: 'Bình 20L - Ắc quy 12Ah', price: 1150000, originalPrice: 1300000, stock: 50, sku: 'KAS-KS20-12' },
      { id: 'v-kas-lithium', name: 'Bình 20L - Pin Lithium Siêu Nhẹ', price: 1650000, stock: 20, sku: 'KAS-KS20-LIT' },
    ],
    equipmentSpecs: {
      capacity: '20 Lít',
      powerType: 'Ắc quy điện',
      pressure: '0.15 - 0.45 Mpa',
      batterySpec: '12V 12Ah (hoạt động 6-8 tiếng)',
      weight: '5.8 kg',
      warrantyMonths: 12,
    }
  }
];
