-- Insert default roles
INSERT INTO roles (name) VALUES ('ROLE_ADMIN') ON DUPLICATE KEY UPDATE name = 'ROLE_ADMIN';
INSERT INTO roles (name) VALUES ('ROLE_CUSTOMER') ON DUPLICATE KEY UPDATE name = 'ROLE_CUSTOMER';
